// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT DIRECTLY.
// To modify details, update paintings.csv in the root folder and run builds.

export interface Painting {
  id: string;
  title: string;
  series: string;
  size: string;
  medium: string;
  price: number;
  formattedPrice: string;
  description: string;
  details: string;
  images: string[];
  status: 'available' | 'sold';
  year: string;
}

export const paintings: Painting[] = [];

