// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT DIRECTLY.
// To modify details, update paintings.csv in the root folder and run builds.

export interface Painting {
  id: string;
  title: string;
  series: string;
  size: string;
  medium: string;
  price: number;
  formattedPrice: string;
  description: string;
  details: string;
  images: string[];
  status: 'available' | 'sold';
  year: string;
}

export const paintings: Painting[] = [
  {
    "id": "echoes-of-closeness",
    "title": "Attachment 1",
    "series": "Attachment",
    "size": "13\"x12\"",
    "medium": "Ink on paper",
    "price": 250,
    "formattedPrice": "$250",
    "description": "Attachment examines the invisible emotional networks formed through trauma, memory, and conditioning, revealing how past experiences continue to shape identity, attachment, and human connection.",
    "details": "* Edition: Original (1/1)\n* Framing: Unframed(with mount)\n* Signed: Signed on both the front and back\n* Certificate of Authenticity: Included",
    "images": [
      "/images/IMG_3269.jpg",
      "/images/IMG_9449.jpg",
      "/images/IMG_9466.jpg"
    ],
    "status": "sold",
    "year": "2026"
  }
];

