'use client';

import { useState } from 'react';
import Image from 'next/image';
import Link from 'next/link';
import Script from 'next/script';
import { Painting } from '../../data/paintings';

interface Props {
  painting: Painting;
}

interface RazorpaySuccessResponse {
  razorpay_order_id: string;
  razorpay_payment_id: string;
  razorpay_signature: string;
}

interface RazorpayFailureResponse {
  error: { description?: string };
}

interface RazorpayInstance {
  open: () => void;
  on: (event: 'payment.failed', handler: (response: RazorpayFailureResponse) => void) => void;
}

interface RazorpayOptions {
  key: string;
  amount: number;
  currency: string;
  name: string;
  description: string;
  order_id: string;
  handler: (response: RazorpaySuccessResponse) => void;
  prefill: { name: string; email: string };
  theme: { color: string };
  modal: { ondismiss: () => void };
}

declare global {
  interface Window {
    Razorpay: new (options: RazorpayOptions) => RazorpayInstance;
  }
}

export default function PaintingDetailClient({ painting }: Props) {
  const [activeImageIndex, setActiveImageIndex] = useState(0);
  const [isInquiryOpen, setIsInquiryOpen] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [formSubmitted, setFormSubmitted] = useState(false);
  const [formError, setFormError] = useState<string | null>(null);
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    phone: '',
    message: `Hello Nazia,\n\nI am interested in acquiring your painting "${painting.title}" from the ${painting.series} series. Please let me know its availability, delivery options, and additional details.\n\nThank you.`
  });

  const [isPayOpen, setIsPayOpen] = useState(false);
  const [isPaying, setIsPaying] = useState(false);
  const [paySuccess, setPaySuccess] = useState<{ paymentId: string } | null>(null);
  const [downloadingInvoice, setDownloadingInvoice] = useState(false);
  const [invoiceError, setInvoiceError] = useState<string | null>(null);
  const [payError, setPayError] = useState<string | null>(null);
  const [payerName, setPayerName] = useState('');
  const [payerEmail, setPayerEmail] = useState('');
  const [shipAddress, setShipAddress] = useState('');
  const [shipCity, setShipCity] = useState('');
  const [shipState, setShipState] = useState('');
  const [shipPincode, setShipPincode] = useState('');
  const [shipCountry, setShipCountry] = useState('');
  const [specialRequest, setSpecialRequest] = useState('');
  const [submittingRequest, setSubmittingRequest] = useState(false);
  const [requestError, setRequestError] = useState<string | null>(null);
  const [requestSent, setRequestSent] = useState(false);
  const [invoiceDownloaded, setInvoiceDownloaded] = useState(false);
  const [razorpayReady, setRazorpayReady] = useState(false);
  const [payCurrency, setPayCurrency] = useState<'USD' | 'INR'>('USD');
  const [inrPreview, setInrPreview] = useState<number | null>(null);
  const [inrPreviewLoading, setInrPreviewLoading] = useState(false);

  const closePay = () => {
    setIsPayOpen(false);
    setPaySuccess(null);
    setPayError(null);
    setPayerName('');
    setPayerEmail('');
    setShipAddress('');
    setShipCity('');
    setShipState('');
    setShipPincode('');
    setShipCountry('');
    setSpecialRequest('');
    setSubmittingRequest(false);
    setRequestError(null);
    setRequestSent(false);
    setPayCurrency('USD');
    setInrPreview(null);
    setInvoiceError(null);
    setInvoiceDownloaded(false);
  };

  // The invoice is generated by our webhook, which usually finishes within a
  // couple seconds of payment but isn't guaranteed to have run by the time
  // this success screen renders — retry a couple times before giving up.
  const downloadInvoice = async (paymentId: string) => {
    setDownloadingInvoice(true);
    setInvoiceError(null);
    try {
      let res: Response | null = null;
      for (let attempt = 0; attempt < 3; attempt++) {
        res = await fetch(`/api/invoice/${encodeURIComponent(paymentId)}`);
        if (res.ok) break;
        await new Promise((r) => setTimeout(r, 2000));
      }
      if (!res || !res.ok) {
        setInvoiceError('Invoice is still being generated — check your email in a moment, or try again shortly.');
        return;
      }
      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${paymentId}.pdf`;
      document.body.appendChild(a);
      a.click();
      a.remove();
      URL.revokeObjectURL(url);
      setInvoiceDownloaded(true);
    } catch (err) {
      setInvoiceError('Failed to download invoice. Please try again.');
    } finally {
      setDownloadingInvoice(false);
    }
  };

  const submitSpecialRequest = async (paymentId: string) => {
    if (!specialRequest.trim()) return;
    setSubmittingRequest(true);
    setRequestError(null);
    try {
      const res = await fetch('/api/special-request', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ paymentId, message: specialRequest.trim() }),
      });
      if (res.ok) {
        setRequestSent(true);
      } else {
        const data = await res.json().catch(() => ({}));
        setRequestError(data.error || 'Failed to send your request. You can still close this window.');
      }
    } catch (err) {
      setRequestError('Failed to send your request. You can still close this window.');
    } finally {
      setSubmittingRequest(false);
    }
  };

  const selectCurrency = async (currency: 'USD' | 'INR') => {
    setPayCurrency(currency);
    setPayError(null);
    if (currency === 'INR' && inrPreview === null) {
      setInrPreviewLoading(true);
      try {
        const res = await fetch('/api/exchange-rate');
        const data = await res.json();
        if (res.ok && typeof data.rate === 'number') {
          setInrPreview(Math.round(painting.price * data.rate));
        }
      } catch (err) {
        // Non-fatal — the real amount still comes back correctly from
        // create-order; this is just a preview.
      } finally {
        setInrPreviewLoading(false);
      }
    }
  };

  const handlePayNow = async () => {
    setPayError(null);
    if (!payerName.trim() || !payerEmail.trim()) {
      setPayError('Please enter your name and email before paying.');
      return;
    }
    if (!shipAddress.trim() || !shipCity.trim() || !shipState.trim() || !shipPincode.trim() || !shipCountry.trim()) {
      setPayError('Please complete your full shipping address, including PIN/ZIP code.');
      return;
    }
    if (!razorpayReady || !window.Razorpay) {
      setPayError('Payment is still loading — please wait a moment and try again.');
      return;
    }

    setIsPaying(true);
    try {
      const orderRes = await fetch('/api/create-order', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          paintingId: painting.id,
          currency: payCurrency,
          payerName,
          payerEmail,
          shipAddress,
          shipCity,
          shipState,
          shipPincode,
          shipCountry,
        }),
      });
      const orderData = await orderRes.json();
      if (!orderRes.ok) {
        setPayError(orderData.error || 'Failed to start payment. Please try again.');
        setIsPaying(false);
        return;
      }

      const razorpay = new window.Razorpay({
        key: process.env.NEXT_PUBLIC_RAZORPAY_KEY_ID || '',
        amount: orderData.amount,
        currency: orderData.currency,
        name: 'ReenArt Studio',
        description: painting.title,
        order_id: orderData.order_id,
        prefill: { name: payerName, email: payerEmail },
        theme: { color: '#c9a84c' },
        handler: async (response) => {
          try {
            const verifyRes = await fetch('/api/verify-payment', {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify(response),
            });
            const verifyData = await verifyRes.json();
            if (verifyRes.ok && verifyData.success) {
              setPaySuccess({ paymentId: response.razorpay_payment_id });
            } else {
              setPayError(verifyData.error || 'Payment could not be verified. Please contact us before retrying.');
            }
          } catch (err) {
            setPayError('Payment could not be verified. Please contact us before retrying.');
          } finally {
            setIsPaying(false);
          }
        },
        modal: {
          ondismiss: () => {
            setIsPaying(false);
          },
        },
      });

      razorpay.on('payment.failed', () => {
        // Razorpay's own error.description can be a raw bank/network decline
        // reason — keep the message simple and actionable instead of
        // surfacing that verbatim.
        setPayError('Transaction failed. Please try again.');
        setIsPaying(false);
      });

      razorpay.open();
    } catch (err) {
      setPayError('Failed to start payment. Please check your connection and try again.');
      setIsPaying(false);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);
    setFormError(null);
    try {
      const fullMessage = formData.phone
        ? `${formData.message}\n\nPhone: ${formData.phone}`
        : formData.message;
      const res = await fetch('/api/contact', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name: formData.name,
          email: formData.email,
          subject: `Artwork Acquisition — ${painting.title}`,
          message: fullMessage,
        }),
      });
      const data = await res.json();
      if (res.ok && data.success) {
        setFormSubmitted(true);
      } else {
        setFormError(data.error || 'Failed to send your inquiry. Please try again.');
      }
    } catch (err) {
      setFormError('Failed to send your inquiry. Please check your connection and try again.');
    } finally {
      setIsSubmitting(false);
    }
  };

  const closeInquiry = () => {
    setIsInquiryOpen(false);
    setFormSubmitted(false);
    setFormData({
      name: '',
      email: '',
      phone: '',
      message: `Hello Nazia,\n\nI am interested in acquiring your painting "${painting.title}" from the ${painting.series} series. Please let me know its availability, delivery options, and additional details.\n\nThank you.`
    });
  };

  return (
    <div className="mx-auto w-full max-w-7xl px-6 py-12 md:px-12 animate-fade-in flex-1 flex flex-col justify-start">
      <Script
        src="https://checkout.razorpay.com/v1/checkout.js"
        strategy="afterInteractive"
        onLoad={() => setRazorpayReady(true)}
      />
      {/* Breadcrumb Navigation */}
      <nav className="mb-10 text-[10px] uppercase tracking-widest text-muted flex items-center gap-2">
        <Link href="/gallery" className="hover:text-foreground transition-colors">Gallery</Link>
        <span>/</span>
        <Link href={`/gallery?series=${encodeURIComponent(painting.series)}`} className="hover:text-foreground transition-colors">{painting.series}</Link>
        <span>/</span>
        <span className="text-foreground font-medium">{painting.title}</span>
      </nav>

      {/* Main Layout Split */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 lg:gap-16 items-start">
        {/* Left Side: Images View */}
        <div className="lg:col-span-7 flex flex-col gap-4">
          <div className="relative aspect-[4/5] w-full overflow-hidden bg-neutral-100 dark:bg-neutral-900 border border-border-subtle">
            <Image
              src={painting.images[activeImageIndex]}
              alt={`${painting.title} - View ${activeImageIndex + 1}`}
              fill
              priority
              sizes="(max-width: 1024px) 100vw, 60vw"
              className="object-cover transition-all duration-500"
            />
            {painting.status === 'sold' && (
              <span className="absolute top-6 right-6 bg-background/95 text-foreground text-xs uppercase tracking-widest px-4 py-2 font-light border border-border-subtle">
                Sold
              </span>
            )}
          </div>

          {/* Thumbnails Row */}
          {painting.images.length > 1 && (
            <div className="flex gap-4 overflow-x-auto pb-2">
              {painting.images.map((img, idx) => (
                <button
                  key={idx}
                  onClick={() => setActiveImageIndex(idx)}
                  className={`relative w-20 h-20 overflow-hidden bg-neutral-100 border transition-all shrink-0 ${
                    activeImageIndex === idx ? 'border-accent ring-1 ring-accent/30' : 'border-border-subtle hover:border-accent/50'
                  }`}
                >
                  <Image
                    src={img}
                    alt={`Thumbnail view ${idx + 1}`}
                    fill
                    sizes="80px"
                    className="object-cover"
                  />
                </button>
              ))}
            </div>
          )}
        </div>

        {/* Right Side: Metadata and Info */}
        <div className="lg:col-span-5 flex flex-col gap-8 lg:sticky lg:top-28">
          <div className="flex flex-col gap-3">
            <span className="text-[10px] tracking-[0.3em] uppercase text-accent font-medium">{painting.series} Series • {painting.year}</span>
            <h1 className="font-serif text-3xl md:text-5xl font-light tracking-wide text-foreground">
              {painting.title}
            </h1>
            <div className="flex items-center gap-4 mt-2">
              <span className="text-xl font-light text-accent tracking-wide tabular-nums">{painting.formattedPrice}</span>
              <span className={`text-[10px] uppercase tracking-widest px-2.5 py-0.5 border font-light ${
                painting.status === 'available'
                  ? 'border-emerald-500/20 bg-emerald-500/5 text-emerald-600 dark:text-emerald-400'
                  : 'border-neutral-500/20 bg-neutral-500/5 text-neutral-500'
              }`}>
                {painting.status}
              </span>
            </div>
          </div>

          {/* Specifications Card */}
          <div className="border-t border-b border-border-subtle py-6">
            <h3 className="text-xs uppercase tracking-widest text-foreground font-medium mb-4">Artwork Details</h3>
            <dl className="grid grid-cols-2 gap-y-4 gap-x-2 text-xs font-light text-muted tracking-wide">
              <div>
                <dt className="uppercase text-[9px] text-muted tracking-widest font-normal mb-1">Medium</dt>
                <dd className="text-foreground">{painting.medium}</dd>
              </div>
              <div>
                <dt className="uppercase text-[9px] text-muted tracking-widest font-normal mb-1">Dimensions</dt>
                <dd className="text-foreground">{painting.size}</dd>
              </div>
              <div>
                <dt className="uppercase text-[9px] text-muted tracking-widest font-normal mb-1">Authenticity</dt>
                <dd className="text-foreground">Signed & Certified</dd>
              </div>
              <div>
                <dt className="uppercase text-[9px] text-muted tracking-widest font-normal mb-1">Origin</dt>
                <dd className="text-foreground">Artist's Studio</dd>
              </div>
            </dl>
          </div>

          {/* Description */}
          <div className="flex flex-col gap-3">
            <h3 className="text-xs uppercase tracking-widest text-foreground font-medium">Concept & Inspiration</h3>
            <p className="text-sm font-light text-muted tracking-wide leading-relaxed">
              {painting.description}
            </p>
          </div>

          {/* Shipping Info */}
          <div className="flex flex-col gap-2 bg-white/5 border border-white/10 shadow-[inset_0_1px_0_rgba(255,255,255,0.06)] p-5">
            <h4 className="text-[10px] uppercase tracking-widest text-accent font-medium">Acquiring this Artwork</h4>
            <p className="text-[11px] font-light text-muted leading-relaxed tracking-wide">
              {painting.details} Free worldwide shipping in custom wood crates or reinforced archival packaging. Ships within 5-7 business days with active tracking and insurance cover.
            </p>
          </div>

          {/* Inquiry / Pay CTA Buttons */}
          {painting.status === 'available' ? (
            <div className="flex flex-col gap-3">
              <button
                onClick={() => setIsPayOpen(true)}
                className="w-full h-12 border border-foreground bg-foreground text-background text-xs uppercase tracking-widest hover:bg-transparent hover:text-foreground transition-all duration-300 font-medium"
              >
                Pay Now — {painting.formattedPrice}
              </button>
              <button
                onClick={() => setIsInquiryOpen(true)}
                className="w-full h-12 border border-border-subtle bg-transparent text-foreground text-xs uppercase tracking-widest hover:border-foreground transition-all duration-300 font-medium"
              >
                Inquire to Acquire
              </button>
            </div>
          ) : (
            <button
              onClick={() => setIsInquiryOpen(true)}
              className="w-full h-12 border border-border-subtle bg-transparent text-muted text-xs uppercase tracking-widest hover:border-foreground hover:text-foreground transition-all duration-300"
            >
              Request Custom Commission
            </button>
          )}
        </div>
      </div>

      {/* Inquiry Modal */}
      {isInquiryOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
          {/* Backdrop */}
          <div 
            className="absolute inset-0 bg-black/60 backdrop-blur-sm transition-opacity"
            onClick={closeInquiry}
          />
          
          {/* Modal content */}
          <div className="relative w-full max-w-lg bg-background/80 backdrop-blur-2xl border border-white/10 p-8 md:p-10 shadow-2xl shadow-black/50 z-10 animate-fade-in max-h-[90vh] overflow-y-auto before:absolute before:inset-0 before:pointer-events-none before:shadow-[inset_0_1px_0_rgba(255,255,255,0.08)]">
            {/* Close Button */}
            <button
              onClick={closeInquiry}
              className="absolute top-6 right-6 text-muted hover:text-foreground hover:scale-115 transition-all text-sm uppercase tracking-widest"
              aria-label="Close modal"
            >
              ✕
            </button>

            {!formSubmitted ? (
              <div className="flex flex-col gap-6">
                <div className="flex flex-col gap-1 pr-6">
                  <span className="text-[9px] uppercase tracking-[0.3em] text-accent font-medium">Acquisition Request</span>
                  <h2 className="font-serif text-2xl font-light tracking-wide text-foreground">
                    Inquire: {painting.title}
                  </h2>
                  <p className="text-[10px] text-muted tracking-wide mt-1">
                    Complete the form below. Nazia will follow up directly regarding shipping estimates and checkout.
                  </p>
                </div>

                <form onSubmit={handleSubmit} className="flex flex-col gap-4">
                  {formError && (
                    <div className="border border-red-400/40 bg-red-500/10 text-red-400 text-xs tracking-wide px-4 py-3">
                      {formError}
                    </div>
                  )}
                  <div className="flex flex-col gap-1.5">
                    <label className="text-[10px] uppercase tracking-widest text-muted font-medium">Your Name *</label>
                    <input
                      type="text"
                      required
                      value={formData.name}
                      onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                      placeholder="e.g. John Doe"
                      className="w-full h-10 border border-border-subtle bg-transparent px-3 text-xs tracking-wide focus:border-accent focus:outline-none transition-colors"
                    />
                  </div>

                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    <div className="flex flex-col gap-1.5">
                      <label className="text-[10px] uppercase tracking-widest text-muted font-medium">Your Email *</label>
                      <input
                        type="email"
                        required
                        value={formData.email}
                        onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                        placeholder="e.g. john@example.com"
                        className="w-full h-10 border border-border-subtle bg-transparent px-3 text-xs tracking-wide focus:border-accent focus:outline-none transition-colors"
                      />
                    </div>
                    <div className="flex flex-col gap-1.5">
                      <label className="text-[10px] uppercase tracking-widest text-muted font-medium">Your Phone (Optional)</label>
                      <input
                        type="tel"
                        value={formData.phone}
                        onChange={(e) => setFormData({ ...formData, phone: e.target.value })}
                        placeholder="e.g. +1 555-0199"
                        className="w-full h-10 border border-border-subtle bg-transparent px-3 text-xs tracking-wide focus:border-accent focus:outline-none transition-colors"
                      />
                    </div>
                  </div>

                  <div className="flex flex-col gap-1.5">
                    <label className="text-[10px] uppercase tracking-widest text-muted font-medium">Message *</label>
                    <textarea
                      required
                      rows={5}
                      value={formData.message}
                      onChange={(e) => setFormData({ ...formData, message: e.target.value })}
                      className="w-full border border-border-subtle bg-transparent p-3 text-xs tracking-wide focus:border-accent focus:outline-none transition-colors resize-none leading-relaxed"
                    />
                  </div>

                  <button
                    type="submit"
                    disabled={isSubmitting}
                    className="w-full h-12 mt-2 bg-foreground text-background border border-foreground text-xs uppercase tracking-widest font-medium hover:bg-transparent hover:text-foreground disabled:opacity-50 transition-all duration-300"
                  >
                    {isSubmitting ? 'Sending Request...' : 'Send Inquiry'}
                  </button>
                </form>
              </div>
            ) : (
              <div className="flex flex-col items-center justify-center py-8 text-center gap-6">
                {/* Success Icon */}
                <div className="w-16 h-16 rounded-full border border-accent/30 bg-accent/5 flex items-center justify-center text-accent text-2xl font-light">
                  ✓
                </div>
                <div className="flex flex-col gap-2">
                  <h3 className="font-serif text-2xl font-light tracking-wide text-foreground">Inquiry Received</h3>
                  <p className="text-xs font-light text-muted leading-relaxed max-w-sm tracking-wide">
                    Thank you for your interest in Nazia's work. A personal response and invoice outline will be sent to <strong>{formData.email}</strong> within 24 to 48 hours.
                  </p>
                </div>
                <button
                  onClick={closeInquiry}
                  className="mt-4 border border-border-subtle px-6 py-2.5 text-[10px] uppercase tracking-widest hover:border-foreground transition-colors font-medium"
                >
                  Close Window
                </button>
              </div>
            )}
          </div>
        </div>
      )}

      {/* Payment Modal */}
      {isPayOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
          {/* Backdrop */}
          <div
            className="absolute inset-0 bg-black/60 backdrop-blur-sm transition-opacity"
            onClick={() => { if (!paySuccess || invoiceDownloaded) closePay(); }}
          />

          {/* Modal content */}
          <div className="relative w-full max-w-lg bg-background/80 backdrop-blur-2xl border border-white/10 p-8 md:p-10 shadow-2xl shadow-black/50 z-10 animate-fade-in max-h-[90vh] overflow-y-auto before:absolute before:inset-0 before:pointer-events-none before:shadow-[inset_0_1px_0_rgba(255,255,255,0.08)]">
            {/* Close Button */}
            <button
              onClick={() => { if (!paySuccess || invoiceDownloaded) closePay(); }}
              disabled={!!paySuccess && !invoiceDownloaded}
              title={paySuccess && !invoiceDownloaded ? 'Download your invoice first' : undefined}
              className="absolute top-6 right-6 text-muted hover:text-foreground hover:scale-115 transition-all text-sm uppercase tracking-widest disabled:opacity-30 disabled:hover:scale-100 disabled:cursor-not-allowed"
              aria-label="Close modal"
            >
              ✕
            </button>

            {!paySuccess ? (
              <div className="flex flex-col gap-6">
                <div className="flex flex-col gap-1 pr-6">
                  <span className="text-[9px] uppercase tracking-[0.3em] text-accent font-medium">Secure Checkout</span>
                  <h2 className="font-serif text-2xl font-light tracking-wide text-foreground">
                    Pay for {painting.title}
                  </h2>
                  <p className="text-[10px] text-muted tracking-wide mt-1">
                    {painting.formattedPrice} — payment processed securely via Razorpay.
                  </p>
                </div>

                {payError && (
                  <div className="border border-red-400/40 bg-red-500/10 text-red-400 text-xs tracking-wide px-4 py-3">
                    {payError}
                  </div>
                )}

                <div className="flex flex-col gap-4">
                  <div className="flex flex-col gap-1.5">
                    <label className="text-[10px] uppercase tracking-widest text-muted font-medium">Pay In</label>
                    <div className="grid grid-cols-2 gap-2">
                      <button
                        type="button"
                        onClick={() => selectCurrency('USD')}
                        className={`h-11 border text-xs uppercase tracking-widest transition-colors ${
                          payCurrency === 'USD'
                            ? 'border-foreground bg-foreground text-background font-medium'
                            : 'border-border-subtle text-muted hover:border-foreground hover:text-foreground'
                        }`}
                      >
                        USD — {painting.formattedPrice}
                        <span className="block text-[9px] normal-case tracking-normal opacity-70">International card</span>
                      </button>
                      <button
                        type="button"
                        onClick={() => selectCurrency('INR')}
                        className={`h-11 border text-xs uppercase tracking-widest transition-colors ${
                          payCurrency === 'INR'
                            ? 'border-foreground bg-foreground text-background font-medium'
                            : 'border-border-subtle text-muted hover:border-foreground hover:text-foreground'
                        }`}
                      >
                        {inrPreviewLoading ? '…' : inrPreview !== null ? `₹${inrPreview.toLocaleString('en-IN')}` : 'INR'}
                        <span className="block text-[9px] normal-case tracking-normal opacity-70">UPI / Cards / Netbanking</span>
                      </button>
                    </div>
                  </div>

                  <div className="flex flex-col gap-1.5">
                    <label className="text-[10px] uppercase tracking-widest text-muted font-medium">Your Name *</label>
                    <input
                      type="text"
                      required
                      value={payerName}
                      onChange={(e) => setPayerName(e.target.value)}
                      placeholder="e.g. John Doe"
                      className="w-full h-10 border border-border-subtle bg-transparent px-3 text-xs tracking-wide focus:border-accent focus:outline-none transition-colors"
                    />
                  </div>
                  <div className="flex flex-col gap-1.5">
                    <label className="text-[10px] uppercase tracking-widest text-muted font-medium">Your Email *</label>
                    <input
                      type="email"
                      required
                      value={payerEmail}
                      onChange={(e) => setPayerEmail(e.target.value)}
                      placeholder="e.g. john@example.com"
                      className="w-full h-10 border border-border-subtle bg-transparent px-3 text-xs tracking-wide focus:border-accent focus:outline-none transition-colors"
                    />
                  </div>

                  <div className="flex flex-col gap-1.5">
                    <label className="text-[10px] uppercase tracking-widest text-muted font-medium">Shipping Address *</label>
                    <input
                      type="text"
                      required
                      value={shipAddress}
                      onChange={(e) => setShipAddress(e.target.value)}
                      placeholder="Street address, apartment, etc."
                      className="w-full h-10 border border-border-subtle bg-transparent px-3 text-xs tracking-wide focus:border-accent focus:outline-none transition-colors"
                    />
                  </div>

                  <div className="grid grid-cols-2 gap-4">
                    <div className="flex flex-col gap-1.5">
                      <label className="text-[10px] uppercase tracking-widest text-muted font-medium">City *</label>
                      <input
                        type="text"
                        required
                        value={shipCity}
                        onChange={(e) => setShipCity(e.target.value)}
                        placeholder="e.g. Delhi"
                        className="w-full h-10 border border-border-subtle bg-transparent px-3 text-xs tracking-wide focus:border-accent focus:outline-none transition-colors"
                      />
                    </div>
                    <div className="flex flex-col gap-1.5">
                      <label className="text-[10px] uppercase tracking-widest text-muted font-medium">State / Province *</label>
                      <input
                        type="text"
                        required
                        value={shipState}
                        onChange={(e) => setShipState(e.target.value)}
                        placeholder="e.g. Delhi"
                        className="w-full h-10 border border-border-subtle bg-transparent px-3 text-xs tracking-wide focus:border-accent focus:outline-none transition-colors"
                      />
                    </div>
                  </div>

                  <div className="grid grid-cols-2 gap-4">
                    <div className="flex flex-col gap-1.5">
                      <label className="text-[10px] uppercase tracking-widest text-muted font-medium">PIN / ZIP Code *</label>
                      <input
                        type="text"
                        required
                        value={shipPincode}
                        onChange={(e) => setShipPincode(e.target.value)}
                        placeholder="e.g. 110001"
                        className="w-full h-10 border border-border-subtle bg-transparent px-3 text-xs tracking-wide focus:border-accent focus:outline-none transition-colors"
                      />
                    </div>
                    <div className="flex flex-col gap-1.5">
                      <label className="text-[10px] uppercase tracking-widest text-muted font-medium">Country *</label>
                      <input
                        type="text"
                        required
                        value={shipCountry}
                        onChange={(e) => setShipCountry(e.target.value)}
                        placeholder="e.g. India"
                        className="w-full h-10 border border-border-subtle bg-transparent px-3 text-xs tracking-wide focus:border-accent focus:outline-none transition-colors"
                      />
                    </div>
                  </div>

                  <button
                    onClick={handlePayNow}
                    disabled={isPaying}
                    className="w-full h-12 mt-2 bg-foreground text-background border border-foreground text-xs uppercase tracking-widest font-medium hover:bg-transparent hover:text-foreground disabled:opacity-50 transition-all duration-300"
                  >
                    {isPaying
                      ? 'Processing…'
                      : payCurrency === 'USD'
                        ? `Pay ${painting.formattedPrice}`
                        : `Pay ${inrPreview !== null ? `₹${inrPreview.toLocaleString('en-IN')}` : '…'}`}
                  </button>
                </div>
              </div>
            ) : (
              <div className="flex flex-col items-center justify-center py-8 text-center gap-6">
                {/* Success Icon */}
                <div className="w-16 h-16 rounded-full border border-accent/30 bg-accent/5 flex items-center justify-center text-accent text-2xl font-light">
                  ✓
                </div>
                <div className="flex flex-col gap-2">
                  <h3 className="font-serif text-2xl font-light tracking-wide text-foreground">Payment Received</h3>
                  <p className="text-xs font-light text-muted leading-relaxed max-w-sm tracking-wide">
                    Thank you for your purchase. Please download your invoice below — Nazia will follow up shortly with shipping details.
                  </p>
                  <p className="text-[10px] font-light text-muted tracking-wide mt-1">
                    Payment ID: {paySuccess.paymentId}
                  </p>
                  {invoiceError && (
                    <p className="text-[10px] font-light text-red-400 tracking-wide mt-1">{invoiceError}</p>
                  )}
                  {!invoiceDownloaded && !invoiceError && (
                    <p className="text-[10px] font-light text-accent tracking-wide mt-1">
                      Download your invoice to continue.
                    </p>
                  )}
                </div>

                {invoiceDownloaded && !requestSent && (
                  <div className="w-full max-w-sm flex flex-col gap-2 text-left">
                    <label className="text-[10px] uppercase tracking-widest text-muted font-medium">Special Request (Optional)</label>
                    <textarea
                      rows={3}
                      value={specialRequest}
                      onChange={(e) => setSpecialRequest(e.target.value)}
                      placeholder="Framing preferences, delivery instructions, gift note, etc."
                      className="w-full border border-border-subtle bg-transparent p-3 text-xs tracking-wide focus:border-accent focus:outline-none transition-colors resize-none leading-relaxed"
                    />
                    {requestError && (
                      <p className="text-[10px] font-light text-red-400 tracking-wide">{requestError}</p>
                    )}
                    {specialRequest.trim() && (
                      <button
                        onClick={() => submitSpecialRequest(paySuccess.paymentId)}
                        disabled={submittingRequest}
                        className="self-start border border-border-subtle px-4 py-2 text-[10px] uppercase tracking-widest hover:border-foreground transition-colors font-medium disabled:opacity-50"
                      >
                        {submittingRequest ? 'Sending…' : 'Send Request'}
                      </button>
                    )}
                  </div>
                )}
                {requestSent && (
                  <p className="text-[10px] font-light text-accent tracking-wide">✓ Your request has been sent to Nazia.</p>
                )}

                <div className="flex gap-3 mt-4">
                  <button
                    onClick={() => downloadInvoice(paySuccess.paymentId)}
                    disabled={downloadingInvoice}
                    className="border border-accent/40 bg-accent/5 text-accent px-6 py-2.5 text-[10px] uppercase tracking-widest hover:border-accent transition-colors font-medium disabled:opacity-50"
                  >
                    {downloadingInvoice ? 'Preparing…' : invoiceDownloaded ? 'Download Again' : 'Download Invoice (PDF)'}
                  </button>
                  <button
                    onClick={closePay}
                    disabled={!invoiceDownloaded}
                    title={!invoiceDownloaded ? 'Download your invoice first' : undefined}
                    className="border border-border-subtle px-6 py-2.5 text-[10px] uppercase tracking-widest hover:border-foreground transition-colors font-medium disabled:opacity-40 disabled:cursor-not-allowed disabled:hover:border-border-subtle"
                  >
                    Close Window
                  </button>
                </div>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
